sonar.projectKey=soxnajarrahbousso-dotcom_todolist
sonar.organization=soxnajarrahbousso-dotcom
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx
sonar.typescript.lcov.reportPaths=coverage/lcov.info